//Aliases
#define DK_plus MINUS
#define DK_minus FSLH
#define DK_astrk PIPE
#define DK_qmark UNDER
#define DK_caret RBRC
#define DK_equal RPAR
#define DK_lpar ASTRK
#define DK_rpar LPAR
#define DK_flsh AMPS
#define DK_sqt BACKSLASH 
#define DK_dqt AT
#define DK_dllr GRAVE
#define DK_PAR_B LS(8)
#define DK_PAR_E AMPS
#define DK_CUR_B AMPS
#define DK_CUR_E AMPS
#define DK_SQB_B AMPS
#define DK_SQB_E AMPS
#define DK_HASH AMPS
#define DK_SNAB AMPS
