//Aliases
#define DK_plus MINUS
#define DK_minus FSLH
#define DK_astrk PIPE
#define DK_qmark UNDER
#define DK_caret RBRC
#define DK_equal RPAR
#define DK_lpar ASTRK
#define DK_rpar LPAR
#define DK_flsh AMPS
#define DK_sqt BACKSLASH 
#define DK_dqt AT
#define DK_dllr GRAVE
#define DK_PAR_B LS(8)
#define DK_PAR_E LS(9)
#define DK_CUR_B RA(7)
#define DK_CUR_E RA(0)
#define DK_SQB_B RA(8)
#define DK_SQB_E RA(9)
#define DK_HASH LS(3)
#define DK_SNAB RA(2)
#define DK_BACK RA(NON_US_BACKSLASH)
#define DK_LT NON_US_BACKSLASH
#define DK_GT LS(NON_US_BACKSLASH)
